### ISSUE TITLE
Won't load on newest SBCL

### ISSUE THREAD

**Issue by sirherrbatka** [pkhuong/string-case#1]
when attempting to ql:quickload string-case
```; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-VM violated when interning XOR while in package
;     STRING-CASE.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 246, column: 0, position: 10257)
```

**Comment by sabracrolleton** [comment]
Same problem. string-case is used by multiple projects so it is now percolating through the environment.

**Comment by pkhuong** [comment]
I won't have time to fix this until Sunday. If either of you wants to take a stab at a fix, I'll be happy to comment on the fix and merge when it looks good.

**Comment by sirherrbatka** [comment]
I have no idea how to fix that. My guesswork is that 
instead of (sb-vm::inst sb-vm::xor r (char-code y)) there should be (sb-vm::inst sb-vm::two-arg-xor r (char-code y)) but I never took dive into depths of SBCL internals.

**Comment by sirherrbatka** [comment]
Thank you for fixing this bug.
